### ISSUE TITLE
[功能建议] 发布到 F-Droid

### ISSUE THREAD

**Issue by linsui** [wthee/pcr-tool#123]
可以发布到 F-Droid 吗？

**Comment by wthee** [comment]
暂不考虑

**Comment by linsui** [comment]
请问是需要帮助还是有其他原因？

**Comment by wthee** [comment]
> 请问是需要帮助还是有其他原因？

没时间去弄，感觉也没必要，不需要太多渠道下载

**Comment by linsui** [comment]
如果你不反对我可以打包提交。

**Comment by wthee** [comment]
> 如果你不反对我可以打包提交。

还是不用了🤔

**Comment by zay448345045** [comment]
> 如果你不反对我可以打包提交。

在这里提交申请：https://gitlab.com/fdroid/rfp/-/issues
